package practicaenequipocristianvictoraitornico.personal.repository

import practicaenequipocristianvictoraitornico.common.repository.Repository
import practicaenequipocristianvictoraitornico.personal.models.Persona

interface PersonalRepository:Repository <Persona,Long> {
}